In [19]:
import numpy as np

In [20]:
arr = np.array([2,5,6,8,9,5,5])

In [21]:
arr.max()

np.int64(9)

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)

print("Original:", arr)
print("Reshaped:\n", reshaped)

Original: [1 2 3 4 5 6]
Reshaped:
 [[1 2 3]
 [4 5 6]]


In [23]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.linspace(start, stop, num=50)

NameError: name 'start' is not defined

In [ ]:
arr.linspace(0,1,5)

AttributeError: 'numpy.ndarray' object has no attribute 'linspace'

In [ ]:
np.swapaxes(a, 0, 0)

In [ ]:
reshaped = arr.reshape(5,6,5) 

ValueError: cannot reshape array of size 7 into shape (5,6,5)

In [26]:
import numpy as np

arr = np.array([2,5,6,8,9,5,5])

arr.max()

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)

print("Original:", arr)
print("Reshaped:\n", reshaped)

arr.reshape(2,3)

np.linspace(start, stop, num=50)

arr.linspace(0,1,5)

np.swapaxes(a, 0, 0)

reshaped = arr.reshape(5,6,5) 

a = np.array([2,5,6,8,9,5,5])
b = np.swapaxes(2,5,6,)
print("orignal array",a)

arr.shape

Original: [1 2 3 4 5 6]
Reshaped:
 [[1 2 3]
 [4 5 6]]


NameError: name 'start' is not defined

In [10]:
arr.shape

(7,)